// packages/auth-kit/ui/svelte/LoginForm.svelte
<script lang="ts">
  import { buildLoginSchema, extractFieldError } from '../../core/validation.js';
  import TurnstileWidget from './TurnstileWidget.svelte';

  import type { AuthKitRune } from '../../adapters/svelte/create-auth-kit.svelte.js';
  import type { TurnstileFieldConfig } from '../../core/field-config.js';

  let { authKit, turnstile }: { authKit: AuthKitRune; turnstile?: TurnstileFieldConfig } = $props();

  let identifier = $state('');
  let password = $state('');
  let showPassword = $state(false);
  let turnstileToken: string | null = $state(null);
  let fieldErrors: Record<string, string> = $state({});

  
  /** Clears a field's stale error message as soon as the user edits it, instead of leaving it displayed until the next submit. */
  function clearError(key: string): void {
    if (key in fieldErrors) {
      const { [key]: _removed, ...rest } = fieldErrors;
      fieldErrors = rest;
    }
  }

  /** Validates a single field on blur — shows that field's error immediately instead of waiting for submit. */
  function validateField(key: string): void {
    const result = buildLoginSchema().safeParse({ identifier, password });
    const message = extractFieldError(result, key);
    if (message) {
      fieldErrors = { ...fieldErrors, [key]: message };
    } else {
      clearError(key);
    }
  }

  const flow = $derived(authKit.state.login);

  function handleSubmit(event: SubmitEvent): void {
    event.preventDefault();
    const result = buildLoginSchema().safeParse({ identifier, password });
    if (!result.success) {
      fieldErrors = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
      return;
    }
    fieldErrors = {};
    void authKit.login({ identifier, password, turnstileToken }).catch(() => {});
  }
</script>

<!-- Headless variant — no CSS classes, fully consumer-styleable. Same props/behavior across every presentation. -->
<form onsubmit={handleSubmit} novalidate>
  <div>
    <label for="auth-kit-login-identifier">Correo electrónico o nombre de usuario</label>
    <input id="auth-kit-login-identifier" type="text" bind:value={identifier} oninput={() => clearError('identifier')} onblur={() => validateField('identifier')} autocomplete="username" />
    {#if fieldErrors.identifier}<p role="alert">{fieldErrors.identifier}</p>{/if}
  </div>
  <div>
    <label for="auth-kit-login-password">Contraseña</label>
    <input
      id="auth-kit-login-password"
      type={showPassword ? 'text' : 'password'}
      bind:value={password} oninput={() => clearError('password')} onblur={() => validateField('password')}
      autocomplete="current-password"
    />
    <button type="button" onclick={() => (showPassword = !showPassword)}>{showPassword ? 'Ocultar' : 'Mostrar'}</button>
    {#if fieldErrors.password}<p role="alert">{fieldErrors.password}</p>{/if}
  </div>
  {#if turnstile?.enabled}
    <TurnstileWidget siteKey={turnstile.siteKey} theme={turnstile.theme} mode={turnstile.mode} onToken={(t) => (turnstileToken = t)} />
  {/if}
  <button type="submit" disabled={flow.status === 'submitting'}>
    {flow.status === 'submitting' ? 'Iniciando sesión…' : 'Iniciar sesión'}
  </button>
  {#if flow.status === 'error' && flow.error}<p role="alert">{flow.error.message}</p>{/if}
  {#if flow.status === 'success'}<p>Sesión iniciada.</p>{/if}
</form>

// packages/auth-kit/ui/vue/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue';

import { buildLoginSchema, extractFieldError } from '../../core/validation.js';
import TurnstileWidget from './TurnstileWidget.vue';

import type { UseAuthKitResult } from '../../adapters/vue/use-auth-kit.js';
import type { TurnstileFieldConfig } from '../../core/field-config.js';

const props = defineProps<{ authKit: UseAuthKitResult; turnstile?: TurnstileFieldConfig }>();

const identifier = ref('');
const password = ref('');
const showPassword = ref(false);
const turnstileToken = ref<string | null>(null);
const fieldErrors = ref<Record<string, string>>({});


/** Clears a field's stale error message as soon as the user edits it, instead of leaving it displayed until the next submit. */
function clearError(key: string): void {
  if (key in fieldErrors.value) {
    const next = { ...fieldErrors.value };
    delete next[key];
    fieldErrors.value = next;
  }
}

/** Validates a single field on blur — shows that field's error immediately instead of waiting for submit. */
function validateField(key: string): void {
  const result = buildLoginSchema().safeParse({ identifier: identifier.value, password: password.value });
  const message = extractFieldError(result, key);
  if (message) {
    fieldErrors.value = { ...fieldErrors.value, [key]: message };
  } else {
    clearError(key);
  }
}

function handleSubmit(): void {
  const result = buildLoginSchema().safeParse({ identifier: identifier.value, password: password.value });
  if (!result.success) {
    fieldErrors.value = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
    return;
  }
  fieldErrors.value = {};
  void props.authKit
    .login({ identifier: identifier.value, password: password.value, turnstileToken: turnstileToken.value })
    .catch(() => {});
}
</script>

<!-- Headless variant — no CSS classes, fully consumer-styleable. Same props/behavior across every presentation. -->
<template>
  <form novalidate @submit.prevent="handleSubmit">
    <div>
      <label for="auth-kit-login-identifier">Correo electrónico o nombre de usuario</label>
      <input id="auth-kit-login-identifier" v-model="identifier" @input="clearError('identifier')" @blur="validateField('identifier')" type="text" autocomplete="username" />
      <p v-if="fieldErrors.identifier" role="alert">{{ fieldErrors.identifier }}</p>
    </div>
    <div>
      <label for="auth-kit-login-password">Contraseña</label>
      <input id="auth-kit-login-password" v-model="password" @input="clearError('password')" @blur="validateField('password')" :type="showPassword ? 'text' : 'password'" autocomplete="current-password" />
      <button type="button" @click="showPassword = !showPassword">{{ showPassword ? 'Ocultar' : 'Mostrar' }}</button>
      <p v-if="fieldErrors.password" role="alert">{{ fieldErrors.password }}</p>
    </div>
    <TurnstileWidget
      v-if="turnstile?.enabled"
      :site-key="turnstile.siteKey"
      :theme="turnstile.theme"
      :mode="turnstile.mode"
      @token="(t) => (turnstileToken = t)"
    />
    <button type="submit" :disabled="authKit.state.value.login.status === 'submitting'">
      {{ authKit.state.value.login.status === 'submitting' ? 'Iniciando sesión…' : 'Iniciar sesión' }}
    </button>
    <p v-if="authKit.state.value.login.status === 'error' && authKit.state.value.login.error" role="alert">
      {{ authKit.state.value.login.error.message }}
    </p>
    <p v-if="authKit.state.value.login.status === 'success'">Sesión iniciada.</p>
  </form>
</template>
