// packages/auth-kit/ui/angular/vanilla/reset-password-form.component.ts
import { NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';

import { buildResetPasswordSchema, extractFieldError } from '../../../core/validation.js';

import type { AuthKitService } from '../../../adapters/angular/auth-kit.service.js';
import type { PasswordPolicy } from '../../../core/validation.js';

/** Vanilla CSS variant — same props/behavior as headless, styled with `auth-kit-*` classes. */
@Component({
  selector: 'auth-kit-reset-password-form',
  standalone: true,
  imports: [NgIf],
  template: `
    <form novalidate class="auth-kit-form" (submit)="handleSubmit($event)">
      <label class="auth-kit-field" for="auth-kit-reset-new">
        Contraseña nueva
        <span class="auth-kit-field__row">
          <input
            id="auth-kit-reset-new"
            [type]="showPassword ? 'text' : 'password'"
            autocomplete="new-password"
            class="auth-kit-input"
            [value]="newPassword"
            (input)="newPassword = $any($event.target).value; clearError('newPassword')" (blur)="validateField('newPassword')"
          />
          <button type="button" class="auth-kit-button auth-kit-button--ghost" (click)="showPassword = !showPassword">{{ showPassword ? 'Ocultar' : 'Mostrar' }}</button>
        </span>
      </label>
      <p *ngIf="fieldErrors['newPassword']" class="auth-kit-error">{{ fieldErrors['newPassword'] }}</p>

      <label class="auth-kit-field" for="auth-kit-reset-confirm">
        Confirmar contraseña nueva
        <input
          id="auth-kit-reset-confirm"
          [type]="showPassword ? 'text' : 'password'"
          autocomplete="new-password"
          class="auth-kit-input"
          [value]="confirmPassword"
          (input)="confirmPassword = $any($event.target).value; clearError('confirmPassword')" (blur)="validateField('confirmPassword')"
        />
      </label>
      <p *ngIf="fieldErrors['confirmPassword']" class="auth-kit-error">{{ fieldErrors['confirmPassword'] }}</p>

      <button type="submit" [disabled]="authKit.state().resetPassword.status === 'submitting'" class="auth-kit-button auth-kit-button--primary">
        {{ authKit.state().resetPassword.status === 'submitting' ? 'Restableciendo…' : 'Restablecer contraseña' }}
      </button>
      <p *ngIf="authKit.state().resetPassword.status === 'error' && authKit.state().resetPassword.error" class="auth-kit-error">
        {{ authKit.state().resetPassword.error?.message }}
      </p>
      <p *ngIf="authKit.state().resetPassword.status === 'success'" class="auth-kit-success">Contraseña restablecida.</p>
    </form>
  `,
})
export class ResetPasswordFormComponent {
  @Input({ required: true }) authKit!: AuthKitService;
  @Input({ required: true }) token!: string;
  @Input() passwordPolicy?: PasswordPolicy;

  newPassword = '';
  confirmPassword = '';
  showPassword = false;
  fieldErrors: Record<string, string> = {};

  
  /** Clears a field's stale error message as soon as the user edits it, instead of leaving it displayed until the next submit. */
  clearError(key: string): void {
    if (key in this.fieldErrors) {
      const next = { ...this.fieldErrors };
      delete next[key];
      this.fieldErrors = next;
    }
  }

  /** Validates a single field on blur — shows that field's error immediately instead of waiting for submit. */
  validateField(key: string): void {
    const result = buildResetPasswordSchema({ passwordPolicy: this.passwordPolicy }).safeParse({ newPassword: this.newPassword, confirmPassword: this.confirmPassword });
    const message = extractFieldError(result, key);
    if (message) {
      this.fieldErrors = { ...this.fieldErrors, [key]: message };
    } else {
      this.clearError(key);
    }
  }

  handleSubmit(event: Event): void {
    event.preventDefault();
    const result = buildResetPasswordSchema({ passwordPolicy: this.passwordPolicy }).safeParse({
      newPassword: this.newPassword,
      confirmPassword: this.confirmPassword,
    });
    if (!result.success) {
      this.fieldErrors = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
      return;
    }
    this.fieldErrors = {};
    void this.authKit.resetPassword({ token: this.token, newPassword: this.newPassword }).catch(() => {});
  }
}

// packages/auth-kit/ui/vue/ResetPasswordForm.vue
<script setup lang="ts">
import { ref } from 'vue';

import { buildResetPasswordSchema, extractFieldError } from '../../core/validation.js';

import type { UseAuthKitResult } from '../../adapters/vue/use-auth-kit.js';
import type { PasswordPolicy } from '../../core/validation.js';

const props = defineProps<{ authKit: UseAuthKitResult; token: string; passwordPolicy?: PasswordPolicy }>();

const newPassword = ref('');
const confirmPassword = ref('');
const showPassword = ref(false);
const fieldErrors = ref<Record<string, string>>({});


/** Clears a field's stale error message as soon as the user edits it, instead of leaving it displayed until the next submit. */
function clearError(key: string): void {
  if (key in fieldErrors.value) {
    const next = { ...fieldErrors.value };
    delete next[key];
    fieldErrors.value = next;
  }
}

/** Validates a single field on blur — shows that field's error immediately instead of waiting for submit. */
function validateField(key: string): void {
  const result = buildResetPasswordSchema({ passwordPolicy: props.passwordPolicy }).safeParse({ newPassword: newPassword.value, confirmPassword: confirmPassword.value });
  const message = extractFieldError(result, key);
  if (message) {
    fieldErrors.value = { ...fieldErrors.value, [key]: message };
  } else {
    clearError(key);
  }
}

function handleSubmit(): void {
  const result = buildResetPasswordSchema({ passwordPolicy: props.passwordPolicy }).safeParse({
    newPassword: newPassword.value,
    confirmPassword: confirmPassword.value,
  });
  if (!result.success) {
    fieldErrors.value = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
    return;
  }
  fieldErrors.value = {};
  void props.authKit.resetPassword({ token: props.token, newPassword: newPassword.value }).catch(() => {});
}
</script>

<!-- Headless variant — no CSS classes, fully consumer-styleable. Same props/behavior across every presentation. -->
<template>
  <form novalidate @submit.prevent="handleSubmit">
    <div>
      <label for="auth-kit-reset-new">Contraseña nueva</label>
      <input id="auth-kit-reset-new" v-model="newPassword" @input="clearError('newPassword')" @blur="validateField('newPassword')" :type="showPassword ? 'text' : 'password'" autocomplete="new-password" />
      <button type="button" @click="showPassword = !showPassword">{{ showPassword ? 'Ocultar' : 'Mostrar' }}</button>
      <p v-if="fieldErrors.newPassword" role="alert">{{ fieldErrors.newPassword }}</p>
    </div>
    <div>
      <label for="auth-kit-reset-confirm">Confirmar contraseña nueva</label>
      <input id="auth-kit-reset-confirm" v-model="confirmPassword" @input="clearError('confirmPassword')" @blur="validateField('confirmPassword')" :type="showPassword ? 'text' : 'password'" autocomplete="new-password" />
      <p v-if="fieldErrors.confirmPassword" role="alert">{{ fieldErrors.confirmPassword }}</p>
    </div>
    <button type="submit" :disabled="authKit.state.value.resetPassword.status === 'submitting'">
      {{ authKit.state.value.resetPassword.status === 'submitting' ? 'Restableciendo…' : 'Restablecer contraseña' }}
    </button>
    <p v-if="authKit.state.value.resetPassword.status === 'error' && authKit.state.value.resetPassword.error" role="alert">
      {{ authKit.state.value.resetPassword.error.message }}
    </p>
    <p v-if="authKit.state.value.resetPassword.status === 'success'">Contraseña restablecida.</p>
  </form>
</template>
