// packages/modals/ui/react/Toast.tsx
import { useEffect } from 'react';

import { prefersReducedMotion } from '../a11y/reduced-motion.js';
import { OverlayBody } from './internal/OverlayBody.js';

import type { ModalConfig } from '../../core/types.js';

export interface ToastProps {
  config: ModalConfig;
  onDismiss: (action: 'primary-button' | 'secondary-button' | 'close-button') => void;
}

const DEFAULT_AUTO_DISMISS_MS = 5000;

/** Transient, multi-instance toast for `type: 'toast'`. No focus trap; auto-dismisses (keyed by id). */
export function Toast({ config, onDismiss }: ToastProps) {
  useEffect(() => {
    const ms = config.autoDismissMs ?? DEFAULT_AUTO_DISMISS_MS;
    const timer = setTimeout(() => onDismiss('close-button'), ms);
    return () => clearTimeout(timer);
    // Re-arm only when the toast identity changes — `onDismiss` is idempotent (core/modals.ts), so
    // a stale timer firing right after a manual close is a safe no-op rather than a bug to guard here.
  }, [config.id, config.autoDismissMs]);

  return (
    <div
      role="status"
      aria-live="polite"
      className={`modals-toast${prefersReducedMotion() ? ' modals-no-motion' : ''}`}
    >
      <OverlayBody
        config={config}
        onPrimary={() => onDismiss('primary-button')}
        onSecondary={() => onDismiss('secondary-button')}
        onClose={() => onDismiss('close-button')}
      />
    </div>
  );
}

// packages/modals/ui/svelte/Toast.svelte
<script lang="ts">
  import { prefersReducedMotion } from '../a11y/reduced-motion.js';
  import OverlayBody from './internal/OverlayBody.svelte';

  import type { InteractionAction, ModalConfig } from '../../core/types.js';

  const DEFAULT_AUTO_DISMISS_MS = 5000;

  let {
    config,
    ondismiss,
  }: {
    config: ModalConfig;
    ondismiss: (action: InteractionAction) => void;
  } = $props();

  // Re-arms only when the toast identity changes; `ondismiss` is idempotent (core/modals.ts), so a
  // stale timer firing right after a manual close is a safe no-op.
  $effect(() => {
    const ms = config.autoDismissMs ?? DEFAULT_AUTO_DISMISS_MS;
    const timer = setTimeout(() => ondismiss('close-button'), ms);
    return () => clearTimeout(timer);
  });

  const noMotionClass = $derived(prefersReducedMotion() ? ' modals-no-motion' : '');
</script>

<div role="status" aria-live="polite" class="modals-toast{noMotionClass}">
  <OverlayBody {config} {ondismiss} />
</div>
