// packages/media-picker/ui/react/vanilla/MediaLibraryGrid.tsx
import { basename, formatBytes, formatVariantBadge, sortVariants } from '../../../core/format.js';

import type { JSX } from 'react';
import type { LibraryItem } from '../../../core/media-picker.js';
import type { UseMediaPickerResult } from '../../../adapters/react/use-media-picker.js';

import '../../vanilla-styles.css';

export interface MediaLibraryGridProps {
  picker: UseMediaPickerResult;
  /** Called with the clicked item when `picker.state` was built without `multiple: true`. */
  onSelectSingle?: (item: LibraryItem) => void;
}

/** Vanilla CSS variant: same props/behavior as the headless MediaLibraryGrid, styled with
 * plain `mc-*` classes from `../../vanilla-styles.css` — no framework dependency. A consumer
 * without a bundler can drop `<link rel="stylesheet" href="vanilla-styles.css">` in their HTML
 * instead of relying on this side-effect import. */
export function MediaLibraryGrid({ picker, onSelectSingle }: MediaLibraryGridProps): JSX.Element {
  const { libraryItems, selection, libraryLoading, libraryError } = picker.state;
  const selectedKeys = new Set(selection.map((item) => item.key));

  const handleClick = (item: LibraryItem): void => {
    if (onSelectSingle) {
      onSelectSingle(item);
      return;
    }
    picker.toggleLibrarySelection(item);
  };

  return (
    <div role="grid" aria-busy={libraryLoading} className="mc-grid">
      {libraryError ? (
        <p role="alert" className="mc-alert">
          {libraryError.message}
        </p>
      ) : null}
      {libraryItems.map((item) => {
        const isSelected = selectedKeys.has(item.key);
        return (
          <button
            key={item.key}
            type="button"
            aria-pressed={isSelected}
            data-selected={isSelected}
            onClick={() => handleClick(item)}
            className={`mc-grid__item${isSelected ? ' mc-grid__item--selected' : ''}`}
          >
            {item.mimeType?.startsWith('image/') ? (
              <img src={item.url} alt={item.key} className="mc-grid__thumb" />
            ) : (
              <span>{item.mimeType ?? 'file'}</span>
            )}
            <div className="mc-grid__caption">
              <span className="mc-grid__filename" title={item.key}>
                {basename(item.key)}
              </span>
              <span className="mc-grid__size">{formatBytes(item.size)}</span>
              {item.variants?.length ? (
                <span className="mc-grid__variants">
                  {sortVariants(item.variants).map((variant) => (
                    <span key={variant.key} className="mc-grid__variant" title={variant.label}>
                      {formatVariantBadge(variant)}
                    </span>
                  ))}
                </span>
              ) : null}
            </div>
          </button>
        );
      })}
    </div>
  );
}

// packages/media-picker/ui/svelte/vanilla/MediaLibraryGrid.svelte
<script lang="ts">
  import '../../vanilla-styles.css';
  import { basename, formatBytes, formatVariantBadge, sortVariants } from '../../../core/format.js';
  import type { MediaPickerRune } from '../../../adapters/svelte/create-media-picker.svelte.js';
  import type { LibraryItem } from '../../../core/media-picker.js';

  let {
    picker,
    onSelectSingle,
  }: {
    picker: MediaPickerRune;
    onSelectSingle?: (item: LibraryItem) => void;
  } = $props();

  function handleClick(item: LibraryItem): void {
    if (onSelectSingle) {
      onSelectSingle(item);
      return;
    }
    picker.toggleLibrarySelection(item);
  }

  function isSelected(item: LibraryItem): boolean {
    return picker.state.selection.some((selected) => selected.key === item.key);
  }

</script>

<!-- Vanilla CSS variant: same props/behavior as the headless MediaLibraryGrid. -->
<div role="grid" aria-busy={picker.state.libraryLoading} class="mc-grid">
  {#if picker.state.libraryError}
    <p role="alert" class="mc-alert">{picker.state.libraryError.message}</p>
  {/if}
  {#each picker.state.libraryItems as item (item.key)}
    <button
      type="button"
      aria-pressed={isSelected(item)}
      data-selected={isSelected(item)}
      onclick={() => handleClick(item)}
      class="mc-grid__item"
      class:mc-grid__item--selected={isSelected(item)}
    >
      {#if item.mimeType?.startsWith('image/')}
        <img src={item.url} alt={item.key} class="mc-grid__thumb" />
      {:else}
        <span>{item.mimeType ?? 'file'}</span>
      {/if}
      <div class="mc-grid__caption">
        <span class="mc-grid__filename" title={item.key}>{basename(item.key)}</span>
        <span class="mc-grid__size">{formatBytes(item.size)}</span>
        {#if item.variants?.length}
          <span class="mc-grid__variants">
            {#each sortVariants(item.variants) as variant (variant.key)}
              <span class="mc-grid__variant" title={variant.label}
                >{formatVariantBadge(variant)}</span
              >
            {/each}
          </span>
        {/if}
      </div>
    </button>
  {/each}
</div>
