// packages/media-picker/ui/react/BulkActionsBar.tsx
import type { JSX } from 'react';
import type { UseMediaPickerResult } from '../../adapters/react/use-media-picker.js';

export interface BulkActionsBarProps {
  picker: UseMediaPickerResult;
  multiple: boolean;
  onConfirm?: (items: ReturnType<UseMediaPickerResult['confirmSelection']>) => void;
}

/** Renders nothing unless `multiple` and at least one item is selected. */
export function BulkActionsBar({
  picker,
  multiple,
  onConfirm,
}: BulkActionsBarProps): JSX.Element | null {
  const { selection } = picker.state;
  if (!multiple || selection.length === 0) return null;

  const handleConfirm = (): void => {
    onConfirm?.(picker.confirmSelection());
  };

  return (
    <div role="toolbar" aria-label="Acciones en lote">
      <span>{selection.length} selected</span>
      <button type="button" onClick={handleConfirm}>
        Confirmar
      </button>
      <button type="button" onClick={() => picker.clearSelection()}>
        Vaciar
      </button>
    </div>
  );
}

// packages/media-picker/ui/svelte/BulkActionsBar.svelte
<script lang="ts">
  import type { MediaPickerRune } from '../../adapters/svelte/create-media-picker.svelte.js';
  import type { LibraryItem } from '../../core/media-picker.js';

  let {
    picker,
    multiple,
    onConfirm,
  }: {
    picker: MediaPickerRune;
    multiple: boolean;
    onConfirm?: (items: LibraryItem[]) => void;
  } = $props();

  function handleConfirm(): void {
    onConfirm?.(picker.confirmSelection());
  }
</script>

{#if multiple && picker.state.selection.length > 0}
  <div role="toolbar" aria-label="Acciones en lote">
    <span>{picker.state.selection.length} selected</span>
    <button type="button" onclick={handleConfirm}>Confirmar</button>
    <button type="button" onclick={() => picker.clearSelection()}>Vaciar</button>
  </div>
{/if}
