// packages/auth-kit/ui/vue/TurnstileWidget.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';

import { mountTurnstileWidget, TurnstileController } from '../../core/turnstile.js';

const props = defineProps<{
  siteKey?: string;
  theme?: 'light' | 'dark' | 'auto';
  mode?: 'managed' | 'non-interactive' | 'invisible';
}>();
const emit = defineEmits<{ token: [token: string | null] }>();

const container = ref<HTMLDivElement | null>(null);
const controller = new TurnstileController({ siteKey: props.siteKey, theme: props.theme, mode: props.mode });
let unmountWidget: (() => void) | undefined;

const unsubscribe = controller.subscribe((state) => emit('token', state.token));

onMounted(() => {
  if (container.value) unmountWidget = mountTurnstileWidget(container.value, controller);
});

onBeforeUnmount(() => {
  unsubscribe();
  unmountWidget?.();
});
</script>

<template>
  <div v-if="siteKey" ref="container"></div>
</template>

// packages/auth-kit/ui/svelte/TurnstileWidget.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';

  import { mountTurnstileWidget, TurnstileController } from '../../core/turnstile.js';

  let {
    siteKey,
    theme,
    mode,
    onToken,
  }: {
    siteKey?: string;
    theme?: 'light' | 'dark' | 'auto';
    mode?: 'managed' | 'non-interactive' | 'invisible';
    onToken: (token: string | null) => void;
  } = $props();

  const controller = new TurnstileController({ siteKey, theme, mode });
  let container: HTMLDivElement | undefined = $state();
  let unmountWidget: (() => void) | undefined;

  const unsubscribe = controller.subscribe((state) => onToken(state.token));

  onMount(() => {
    if (container) unmountWidget = mountTurnstileWidget(container, controller);
  });

  onDestroy(() => {
    unsubscribe();
    unmountWidget?.();
  });
</script>

{#if siteKey}
  <div bind:this={container}></div>
{/if}
