// packages/media-picker/ui/svelte/tailwind/VariantFilter.svelte
<script lang="ts">
  /** Valor con el que `ListOptions.variant` pide los originales que no tienen ninguna derivada. */
  const NO_VARIANTS = 'none';

  let {
    options,
    selected,
    onChange,
  }: {
    /** Etiquetas ofrecidas, p. ej. `['large', 'medium', 'thumb']` — las decide quien llama. */
    options: string[];
    /** Etiqueta activa, `'none'`, o `undefined` para no filtrar. */
    selected?: string | undefined;
    /** Recibe `undefined` al volver a «todos», para omitir `variant` de `ListOptions`. */
    onChange: (variant: string | undefined) => void;
  } = $props();

  function handleChange(event: Event): void {
    onChange((event.currentTarget as HTMLSelectElement).value || undefined);
  }
</script>
<!--
  Selector de tamaño derivado para la biblioteca. Alimenta `ListOptions.variant`, que el núcleo
  reenvía tal cual al hook `list` del proveedor.

  Es selección única, no casillas como MimeTypeFilter: filtrar por dos tamaños a la vez no
  significa nada —cada objeto se muestra una sola vez, con sus derivadas dentro— y `'none'` es
  excluyente con cualquier etiqueta por definición.
-->
<label class="inline-flex items-center gap-2 text-xs text-zinc-600">
  Size
  <select
    value={selected ?? ''}
    onchange={handleChange}
    class="rounded-md border border-zinc-300 px-2 py-1 text-xs"
  >
    <option value="">All sizes</option>
    {#each options as label (label)}
      <option value={label}>{label}</option>
    {/each}
    <option value={NO_VARIANTS}>Without derived sizes</option>
  </select>
</label>

// packages/media-picker/ui/react/tailwind/VariantFilter.tsx
import type { JSX } from 'react';

/** Valor con el que `ListOptions.variant` pide los originales que no tienen ninguna derivada. */
export const NO_VARIANTS = 'none';

export interface VariantFilterProps {
  /** Etiquetas ofrecidas, p. ej. `['large', 'medium', 'thumb']` — las decide quien llama. */
  options: string[];
  /** Etiqueta activa, `'none'`, o `undefined` para no filtrar. */
  selected?: string | undefined;
  /** Recibe `undefined` cuando se vuelve a «todos», para omitir `variant` de `ListOptions`. */
  onChange: (variant: string | undefined) => void;
}

/** Variante Tailwind: mismas props y comportamiento que el VariantFilter headless. Selección única: filtrar por dos tamaños a la vez no significa nada, porque cada objeto
 * se muestra una sola vez con sus derivadas dentro. Alimenta `ListOptions.variant`. */
export function VariantFilter({ options, selected, onChange }: VariantFilterProps): JSX.Element {
  return (
    <label className="inline-flex items-center gap-2 text-xs text-zinc-600">
      Size
      <select
        value={selected ?? ''}
        onChange={(event) => onChange(event.target.value || undefined)}
        className="rounded-md border border-zinc-300 px-2 py-1 text-xs"
      >
        <option value="">All sizes</option>
        {options.map((label) => (
          <option key={label} value={label}>
            {label}
          </option>
        ))}
        <option value={NO_VARIANTS}>Without derived sizes</option>
      </select>
    </label>
  );
}
