// packages/media-picker/ui/svelte/vanilla/BulkActionsBar.svelte
<script lang="ts">
  import '../../vanilla-styles.css';
  import type { MediaPickerRune } from '../../../adapters/svelte/create-media-picker.svelte.js';
  import type { LibraryItem } from '../../../core/media-picker.js';

  let {
    picker,
    multiple,
    onConfirm,
  }: {
    picker: MediaPickerRune;
    multiple: boolean;
    onConfirm?: (items: LibraryItem[]) => void;
  } = $props();

  function handleConfirm(): void {
    onConfirm?.(picker.confirmSelection());
  }
</script>

{#if multiple && picker.state.selection.length > 0}
  <div role="toolbar" aria-label="Acciones en lote" class="mc-toolbar">
    <span>{picker.state.selection.length} selected</span>
    <button type="button" onclick={handleConfirm} class="mc-button">Confirmar</button>
    <button type="button" onclick={() => picker.clearSelection()} class="mc-button">Vaciar</button>
  </div>
{/if}

// packages/media-picker/ui/react/vanilla/BulkActionsBar.tsx
import type { JSX } from 'react';
import type { UseMediaPickerResult } from '../../../adapters/react/use-media-picker.js';

import '../../vanilla-styles.css';

export interface BulkActionsBarProps {
  picker: UseMediaPickerResult;
  multiple: boolean;
  onConfirm?: (items: ReturnType<UseMediaPickerResult['confirmSelection']>) => void;
}

/** Vanilla CSS variant of BulkActionsBar — same props/behavior as headless. */
export function BulkActionsBar({
  picker,
  multiple,
  onConfirm,
}: BulkActionsBarProps): JSX.Element | null {
  const { selection } = picker.state;
  if (!multiple || selection.length === 0) return null;

  const handleConfirm = (): void => {
    onConfirm?.(picker.confirmSelection());
  };

  return (
    <div role="toolbar" aria-label="Acciones en lote" className="mc-toolbar">
      <span>{selection.length} selected</span>
      <button type="button" onClick={handleConfirm} className="mc-button">
        Confirmar
      </button>
      <button type="button" onClick={() => picker.clearSelection()} className="mc-button">
        Vaciar
      </button>
    </div>
  );
}
