// packages/media-picker/ui/svelte/vanilla/MimeTypeFilter.svelte
<script lang="ts">
  import '../../vanilla-styles.css';

  let {
    options,
    selected,
    onChange,
  }: {
    options: string[];
    selected: string[];
    onChange: (mimeTypes: string[]) => void;
  } = $props();

  function toggle(mimeType: string): void {
    onChange(
      selected.includes(mimeType)
        ? selected.filter((existing) => existing !== mimeType)
        : [...selected, mimeType],
    );
  }
</script>

<div role="group" aria-label="Filtrar por tipo de archivo" class="mc-mime-group">
  {#each options as mimeType (mimeType)}
    <label class="mc-mime-pill">
      <input type="checkbox" checked={selected.includes(mimeType)} onchange={() => toggle(mimeType)} />
      {mimeType}
    </label>
  {/each}
</div>

// packages/media-picker/ui/react/vanilla/MimeTypeFilter.tsx
import type { JSX } from 'react';

import '../../vanilla-styles.css';

export interface MimeTypeFilterProps {
  options: string[];
  selected: string[];
  onChange: (mimeTypes: string[]) => void;
}

/** Vanilla CSS variant of MimeTypeFilter — same props/behavior as headless. */
export function MimeTypeFilter({ options, selected, onChange }: MimeTypeFilterProps): JSX.Element {
  const toggle = (mimeType: string): void => {
    onChange(
      selected.includes(mimeType)
        ? selected.filter((existing) => existing !== mimeType)
        : [...selected, mimeType],
    );
  };

  return (
    <div role="group" aria-label="Filtrar por tipo de archivo" className="mc-mime-group">
      {options.map((mimeType) => (
        <label key={mimeType} className="mc-mime-pill">
          <input
            type="checkbox"
            checked={selected.includes(mimeType)}
            onChange={() => toggle(mimeType)}
          />
          {mimeType}
        </label>
      ))}
    </div>
  );
}
