// packages/auth-kit/ui/react/tailwind/VerifyEmailForm.tsx
import { TurnstileWidget } from '../TurnstileWidget.js';
import { useVerifyEmailFormState } from '../internal/verify-email-form-state.js';

import type { JSX } from 'react';
import type { UseAuthKitResult } from '../../../adapters/react/use-auth-kit.js';
import type { TurnstileFieldConfig } from '../../../core/field-config.js';

export interface VerifyEmailFormProps {
  authKit: UseAuthKitResult;
  token?: string;
  email?: string;
  turnstile?: TurnstileFieldConfig;
}

const inputClass = 'rounded-md border border-zinc-300 px-2 py-1.5 text-sm';
const labelClass = 'flex flex-col gap-1 text-sm text-zinc-700';
const errorClass = 'text-sm text-red-600';

/** Tailwind variant — same props/behavior as headless, styled with the media-picker zinc palette. */
export function VerifyEmailForm({
  authKit,
  token,
  email: initialEmail,
  turnstile,
}: VerifyEmailFormProps): JSX.Element {
  const {
    email,
    setEmail,
    setTurnstileToken,
    fieldErrors,
    handleResendSubmit,
    verifyFlow,
    resendFlow,
  } = useVerifyEmailFormState({ authKit, token, email: initialEmail });

  return (
    <div className="flex flex-col gap-4">
      {token && (
        <div role="status" className="text-sm">
          {verifyFlow.status === 'submitting' && (
            <p className="text-zinc-700">Verificando tu email…</p>
          )}
          {verifyFlow.status === 'success' && (
            <p className="text-green-600">Tu email está verificado.</p>
          )}
          {verifyFlow.status === 'error' && verifyFlow.error && (
            <p className={errorClass}>{verifyFlow.error.message}</p>
          )}
        </div>
      )}

      <form onSubmit={handleResendSubmit} noValidate className="flex flex-col gap-3">
        <label className={labelClass} htmlFor="auth-kit-resend-email">
          Correo electrónico
          <input
            id="auth-kit-resend-email"
            type="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            autoComplete="email"
            className={inputClass}
          />
        </label>
        {fieldErrors.email && <p className={errorClass}>{fieldErrors.email}</p>}
        {turnstile?.enabled && (
          <TurnstileWidget
            siteKey={turnstile.siteKey}
            theme={turnstile.theme}
            mode={turnstile.mode}
            onToken={setTurnstileToken}
          />
        )}
        <button
          type="submit"
          disabled={resendFlow.status === 'submitting'}
          className="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50 disabled:opacity-50"
        >
          {resendFlow.status === 'submitting' ? 'Enviando…' : 'Reenviar email de verificación'}
        </button>
        {resendFlow.status === 'error' && resendFlow.error && (
          <p className={errorClass}>{resendFlow.error.message}</p>
        )}
        {resendFlow.status === 'success' && (
          <p className="text-sm text-green-600">Email de verificación enviado.</p>
        )}
      </form>
    </div>
  );
}

// packages/auth-kit/ui/svelte/tailwind/VerifyEmailForm.svelte
<script lang="ts">
  import { buildResendVerificationSchema } from '../../../core/validation.js';
  import TurnstileWidget from '../TurnstileWidget.svelte';

  import type { AuthKitRune } from '../../../adapters/svelte/create-auth-kit.svelte.js';
  import type { TurnstileFieldConfig } from '../../../core/field-config.js';

  let {
    authKit,
    token,
    email: initialEmail,
    turnstile,
  }: { authKit: AuthKitRune; token?: string; email?: string; turnstile?: TurnstileFieldConfig } = $props();

  const inputClass = 'rounded-md border border-zinc-300 px-2 py-1.5 text-sm';
  const labelClass = 'flex flex-col gap-1 text-sm text-zinc-700';
  const errorClass = 'text-sm text-red-600';

  let email = $state(initialEmail ?? '');
  let turnstileToken: string | null = $state(null);
  let fieldErrors: Record<string, string> = $state({});
  let verifyAttempted = false;

  const verifyFlow = $derived(authKit.state.verifyEmail);
  const resendFlow = $derived(authKit.state.resendVerification);

  $effect(() => {
    if (!token || verifyAttempted) return;
    verifyAttempted = true;
    void authKit.verifyEmail({ token }).catch(() => {});
  });

  function handleResendSubmit(event: SubmitEvent): void {
    event.preventDefault();
    const result = buildResendVerificationSchema().safeParse({ email });
    if (!result.success) {
      fieldErrors = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
      return;
    }
    fieldErrors = {};
    void authKit.resendVerification({ email, turnstileToken }).catch(() => {});
  }
</script>

<!-- Tailwind variant — same props/behavior as headless, styled with the media-picker zinc palette. -->
<div class="flex flex-col gap-4">
  {#if token}
    <div role="status" class="text-sm">
      {#if verifyFlow.status === 'submitting'}<p class="text-zinc-700">Verificando tu email…</p>{/if}
      {#if verifyFlow.status === 'success'}<p class="text-green-600">Tu email está verificado.</p>{/if}
      {#if verifyFlow.status === 'error' && verifyFlow.error}<p class={errorClass}>{verifyFlow.error.message}</p>{/if}
    </div>
  {/if}

  <form onsubmit={handleResendSubmit} novalidate class="flex flex-col gap-3">
    <label class={labelClass} for="auth-kit-resend-email">
      Correo electrónico
      <input id="auth-kit-resend-email" type="email" bind:value={email} autocomplete="email" class={inputClass} />
    </label>
    {#if fieldErrors.email}<p class={errorClass}>{fieldErrors.email}</p>{/if}
    {#if turnstile?.enabled}
      <TurnstileWidget siteKey={turnstile.siteKey} theme={turnstile.theme} mode={turnstile.mode} onToken={(t) => (turnstileToken = t)} />
    {/if}
    <button
      type="submit"
      disabled={resendFlow.status === 'submitting'}
      class="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50 disabled:opacity-50"
    >
      {resendFlow.status === 'submitting' ? 'Enviando…' : 'Reenviar email de verificación'}
    </button>
    {#if resendFlow.status === 'error' && resendFlow.error}<p class={errorClass}>{resendFlow.error.message}</p>{/if}
    {#if resendFlow.status === 'success'}<p class="text-sm text-green-600">Email de verificación enviado.</p>{/if}
  </form>
</div>
