// packages/modals/ui/svelte/shadcn/BottomBanner.svelte
<script lang="ts">
  import { prefersReducedMotion } from '../../a11y/reduced-motion.js';
  import OverlayBody from './internal/OverlayBody.svelte';

  import type { InteractionAction, ModalConfig } from '../../../core/types.js';

  let {
    config,
    ondismiss,
  }: {
    config: ModalConfig;
    ondismiss: (action: InteractionAction) => void;
  } = $props();

  $effect(() => {
    function onKeydown(event: KeyboardEvent): void {
      if (event.key === 'Escape') ondismiss('close-button');
    }
    document.addEventListener('keydown', onKeydown);
    return () => document.removeEventListener('keydown', onKeydown);
  });

  const noMotionClass = $derived(prefersReducedMotion() ? ' modals-no-motion' : '');
  const transitionClass = $derived(prefersReducedMotion() ? '' : ' transition-transform duration-150');
</script>

<div
  role="region"
  aria-live="polite"
  class="modals-bottom-banner{noMotionClass} fixed bottom-0 left-0 right-0 z-50 border-t border-border bg-card text-card-foreground shadow-sm{transitionClass}"
>
  <OverlayBody {config} {ondismiss} />
</div>

// packages/modals/ui/react/BottomBanner.tsx
import { prefersReducedMotion } from '../a11y/reduced-motion.js';
import { OverlayBody } from './internal/OverlayBody.js';
import { useEscapeKey } from './internal/use-escape-key.js';

import type { ModalConfig } from '../../core/types.js';

export interface BottomBannerProps {
  config: ModalConfig;
  onDismiss: (action: 'primary-button' | 'secondary-button' | 'close-button') => void;
}

/** Sticky banner at the bottom of the viewport for `type: 'bottom-banner'`. Does not steal focus. */
export function BottomBanner({ config, onDismiss }: BottomBannerProps) {
  useEscapeKey(true, () => onDismiss('close-button'));

  return (
    <div
      role="region"
      aria-live="polite"
      className={`modals-bottom-banner${prefersReducedMotion() ? ' modals-no-motion' : ''}`}
    >
      <OverlayBody
        config={config}
        onPrimary={() => onDismiss('primary-button')}
        onSecondary={() => onDismiss('secondary-button')}
        onClose={() => onDismiss('close-button')}
      />
    </div>
  );
}
