// packages/media-picker/ui/svelte/shadcn/MediaLibraryGrid.svelte
<script lang="ts">
  import { Toggle } from 'bits-ui';

  import '../../shadcn-theme.css';
  import { basename, formatBytes, formatVariantBadge, sortVariants } from '../../../core/format.js';
  import type { MediaPickerRune } from '../../../adapters/svelte/create-media-picker.svelte.js';
  import type { LibraryItem } from '../../../core/media-picker.js';

  let {
    picker,
    onSelectSingle,
  }: {
    picker: MediaPickerRune;
    onSelectSingle?: (item: LibraryItem) => void;
  } = $props();

  function handleClick(item: LibraryItem): void {
    if (onSelectSingle) {
      onSelectSingle(item);
      return;
    }
    picker.toggleLibrarySelection(item);
  }

  function isSelected(item: LibraryItem): boolean {
    return picker.state.selection.some((selected) => selected.key === item.key);
  }

</script>

<!--
  Shadcn variant: same props/behavior as the headless MediaLibraryGrid. Each grid item is a
  real `bits-ui` Toggle (not just a styled <button>) — the same primitive shadcn-svelte itself
  uses. Requires `bits-ui` as a peer dependency + shadcn-theme.css + Tailwind loaded.
-->
<div role="grid" aria-busy={picker.state.libraryLoading} class="grid grid-cols-[repeat(auto-fill,minmax(96px,1fr))] gap-2">
  {#if picker.state.libraryError}
    <p role="alert" class="col-span-full text-sm text-destructive">{picker.state.libraryError.message}</p>
  {/if}
  {#each picker.state.libraryItems as item (item.key)}
    <Toggle.Root
      data-selected={isSelected(item)}
      pressed={isSelected(item)}
      onPressedChange={() => handleClick(item)}
      class="rounded-md border p-1 text-left transition-colors {isSelected(item) ? 'border-2 border-ring' : 'border-input hover:border-ring/50'}"
    >
      {#if item.mimeType?.startsWith('image/')}
        <img src={item.url} alt={item.key} class="aspect-square w-full rounded-sm object-cover" />
      {:else}
        <span class="block truncate text-xs text-muted-foreground">{item.mimeType ?? 'file'}</span>
      {/if}
      <div class="mt-1 leading-tight">
        <span class="block truncate text-xs text-foreground" title={item.key}>{basename(item.key)}</span>
        <span class="block text-[11px] text-muted-foreground">{formatBytes(item.size)}</span>
        {#if item.variants?.length}
          <span class="mt-0.5 flex flex-wrap gap-1">
            {#each sortVariants(item.variants) as variant (variant.key)}
              <span
                title={variant.label}
                class="rounded bg-muted px-1 text-[10px] leading-4 text-muted-foreground"
                >{formatVariantBadge(variant)}</span
              >
            {/each}
          </span>
        {/if}
      </div>
    </Toggle.Root>
  {/each}
</div>

// packages/media-picker/ui/react/shadcn/MediaLibraryGrid.tsx
import * as TogglePrimitive from '@radix-ui/react-toggle';

import { basename, formatBytes, formatVariantBadge, sortVariants } from '../../../core/format.js';

import type { JSX } from 'react';
import type { LibraryItem } from '../../../core/media-picker.js';
import type { UseMediaPickerResult } from '../../../adapters/react/use-media-picker.js';

import '../../shadcn-theme.css';

export interface MediaLibraryGridProps {
  picker: UseMediaPickerResult;
  /** Called with the clicked item when `picker.state` was built without `multiple: true`. */
  onSelectSingle?: (item: LibraryItem) => void;
}

/** Shadcn variant: same props/behavior as the headless MediaLibraryGrid. Each grid item is a
 * real `@radix-ui/react-toggle` (not just a styled `<button>`), so `aria-pressed`/`data-state`
 * accessibility semantics come from Radix itself rather than being hand-rolled. Requires
 * `@radix-ui/react-toggle` as a peer dependency + `shadcn-theme.css` + Tailwind loaded. */
export function MediaLibraryGrid({ picker, onSelectSingle }: MediaLibraryGridProps): JSX.Element {
  const { libraryItems, selection, libraryLoading, libraryError } = picker.state;
  const selectedKeys = new Set(selection.map((item) => item.key));

  const handleClick = (item: LibraryItem): void => {
    if (onSelectSingle) {
      onSelectSingle(item);
      return;
    }
    picker.toggleLibrarySelection(item);
  };

  return (
    <div
      role="grid"
      aria-busy={libraryLoading}
      className="grid grid-cols-[repeat(auto-fill,minmax(96px,1fr))] gap-2"
    >
      {libraryError ? (
        <p role="alert" className="col-span-full text-sm text-destructive">
          {libraryError.message}
        </p>
      ) : null}
      {libraryItems.map((item) => {
        const isSelected = selectedKeys.has(item.key);
        return (
          <TogglePrimitive.Root
            key={item.key}
            data-selected={isSelected}
            pressed={isSelected}
            onPressedChange={() => handleClick(item)}
            className={`rounded-md border p-1 text-left transition-colors ${
              isSelected ? 'border-2 border-ring' : 'border-input hover:border-ring/50'
            }`}
          >
            {item.mimeType?.startsWith('image/') ? (
              <img
                src={item.url}
                alt={item.key}
                className="aspect-square w-full rounded-sm object-cover"
              />
            ) : (
              <span className="block truncate text-xs text-muted-foreground">
                {item.mimeType ?? 'file'}
              </span>
            )}
            <div className="mt-1 leading-tight">
              <span className="block truncate text-xs text-foreground" title={item.key}>
                {basename(item.key)}
              </span>
              <span className="block text-[11px] text-muted-foreground">
                {formatBytes(item.size)}
              </span>
              {item.variants?.length ? (
                <span className="mt-0.5 flex flex-wrap gap-1">
                  {sortVariants(item.variants).map((variant) => (
                    <span
                      key={variant.key}
                      title={variant.label}
                      className="rounded bg-muted px-1 text-[10px] leading-4 text-muted-foreground"
                    >
                      {formatVariantBadge(variant)}
                    </span>
                  ))}
                </span>
              ) : null}
            </div>
          </TogglePrimitive.Root>
        );
      })}
    </div>
  );
}
