// packages/media-picker/ui/react/shadcn/MimeTypeFilter.tsx
import type { JSX } from 'react';

import '../../shadcn-theme.css';

export interface MimeTypeFilterProps {
  options: string[];
  selected: string[];
  onChange: (mimeTypes: string[]) => void;
}

/** Shadcn variant of MimeTypeFilter — same props/behavior as headless. */
export function MimeTypeFilter({ options, selected, onChange }: MimeTypeFilterProps): JSX.Element {
  const toggle = (mimeType: string): void => {
    onChange(
      selected.includes(mimeType)
        ? selected.filter((existing) => existing !== mimeType)
        : [...selected, mimeType],
    );
  };

  return (
    <div role="group" aria-label="Filtrar por tipo de archivo" className="flex flex-wrap gap-2">
      {options.map((mimeType) => (
        <label
          key={mimeType}
          className="inline-flex items-center gap-1.5 rounded-full border border-input bg-secondary px-3 py-1 text-xs text-secondary-foreground"
        >
          <input
            type="checkbox"
            checked={selected.includes(mimeType)}
            onChange={() => toggle(mimeType)}
            className="accent-primary"
          />
          {mimeType}
        </label>
      ))}
    </div>
  );
}

// packages/media-picker/ui/svelte/shadcn/MimeTypeFilter.svelte
<script lang="ts">
  import '../../shadcn-theme.css';

  let {
    options,
    selected,
    onChange,
  }: {
    options: string[];
    selected: string[];
    onChange: (mimeTypes: string[]) => void;
  } = $props();

  function toggle(mimeType: string): void {
    onChange(
      selected.includes(mimeType)
        ? selected.filter((existing) => existing !== mimeType)
        : [...selected, mimeType],
    );
  }
</script>

<div role="group" aria-label="Filtrar por tipo de archivo" class="flex flex-wrap gap-2">
  {#each options as mimeType (mimeType)}
    <label class="inline-flex items-center gap-1.5 rounded-full border border-input bg-secondary px-3 py-1 text-xs text-secondary-foreground">
      <input type="checkbox" checked={selected.includes(mimeType)} onchange={() => toggle(mimeType)} class="accent-primary" />
      {mimeType}
    </label>
  {/each}
</div>
