// packages/media-picker/ui/react/tailwind/BulkActionsBar.tsx
import type { JSX } from 'react';
import type { UseMediaPickerResult } from '../../../adapters/react/use-media-picker.js';

export interface BulkActionsBarProps {
  picker: UseMediaPickerResult;
  multiple: boolean;
  onConfirm?: (items: ReturnType<UseMediaPickerResult['confirmSelection']>) => void;
}

/** Tailwind variant of BulkActionsBar — same props/behavior as headless, styled as a toolbar. */
export function BulkActionsBar({
  picker,
  multiple,
  onConfirm,
}: BulkActionsBarProps): JSX.Element | null {
  const { selection } = picker.state;
  if (!multiple || selection.length === 0) return null;

  const handleConfirm = (): void => {
    onConfirm?.(picker.confirmSelection());
  };

  return (
    <div
      role="toolbar"
      aria-label="Acciones en lote"
      className="flex items-center gap-3 rounded-md border border-zinc-200 px-3 py-2"
    >
      <span className="text-sm text-zinc-600">{selection.length} selected</span>
      <button
        type="button"
        onClick={handleConfirm}
        className="rounded-md bg-zinc-900 px-3 py-1.5 text-sm text-white hover:bg-zinc-700"
      >
        Confirmar
      </button>
      <button
        type="button"
        onClick={() => picker.clearSelection()}
        className="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50"
      >
        Vaciar
      </button>
    </div>
  );
}

// packages/media-picker/ui/svelte/tailwind/BulkActionsBar.svelte
<script lang="ts">
  import type { MediaPickerRune } from '../../../adapters/svelte/create-media-picker.svelte.js';
  import type { LibraryItem } from '../../../core/media-picker.js';

  let {
    picker,
    multiple,
    onConfirm,
  }: {
    picker: MediaPickerRune;
    multiple: boolean;
    onConfirm?: (items: LibraryItem[]) => void;
  } = $props();

  function handleConfirm(): void {
    onConfirm?.(picker.confirmSelection());
  }
</script>

{#if multiple && picker.state.selection.length > 0}
  <div role="toolbar" aria-label="Acciones en lote" class="flex items-center gap-3 rounded-md border border-zinc-200 px-3 py-2">
    <span class="text-sm text-zinc-600">{picker.state.selection.length} selected</span>
    <button type="button" onclick={handleConfirm} class="rounded-md bg-zinc-900 px-3 py-1.5 text-sm text-white hover:bg-zinc-700">
      Confirmar
    </button>
    <button type="button" onclick={() => picker.clearSelection()} class="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50">
      Vaciar
    </button>
  </div>
{/if}
