// packages/media-picker/ui/react/tailwind/FolderSelect.tsx
import { useState } from 'react';

import type { JSX } from 'react';
import type { StorageProvider } from '../../../core/provider.js';
import type { UseMediaPickerResult } from '../../../adapters/react/use-media-picker.js';
import { ModernSelect } from '../ModernSelect.js';

export interface FolderSelectProps {
  picker: UseMediaPickerResult;
  provider: StorageProvider;
  value?: string;
  onChange: (folderId: string) => void;
}

/** Tailwind variant of FolderSelect — same props/behavior as headless, styled with utilities. */
export function FolderSelect({
  picker,
  provider,
  value,
  onChange,
}: FolderSelectProps): JSX.Element {
  const [newFolderName, setNewFolderName] = useState('');
  const { folders, foldersLoading, foldersError } = picker.state;
  const canCreate = typeof provider.createFolder === 'function';

  const handleCreate = async (): Promise<void> => {
    const name = newFolderName.trim();
    if (!name) return;
    const folder = await picker.createFolder(provider, name);
    setNewFolderName('');
    onChange(folder.id);
  };

  return (
    <div className="flex flex-wrap items-center gap-2">
      <ModernSelect
        value={value ?? ''}
        disabled={foldersLoading}
        onChange={onChange}
        options={[
          { value: '', label: 'Todas las carpetas' },
          ...folders.map((folder) => ({ value: folder.id, label: folder.name })),
        ]}
        placeholder="Todas las carpetas"
      />
      {foldersError ? (
        <p role="alert" className="text-sm text-red-600">
          {foldersError.message}
        </p>
      ) : null}
      {canCreate ? (
        <span className="flex items-center gap-2">
          <input
            type="text"
            value={newFolderName}
            placeholder="Nueva carpeta"
            onChange={(event) => setNewFolderName(event.target.value)}
            className="rounded-md border border-zinc-300 px-2 py-1.5 text-sm"
          />
          <button
            type="button"
            onClick={() => void handleCreate()}
            className="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50"
          >
            Crear
          </button>
        </span>
      ) : null}
    </div>
  );
}

// packages/media-picker/ui/svelte/tailwind/FolderSelect.svelte
<script lang="ts">
  import type { MediaPickerRune } from '../../../adapters/svelte/create-media-picker.svelte.js';
  import type { StorageProvider } from '../../../core/provider.js';
  import ModernSelect from '../ModernSelect.svelte';

  let {
    picker,
    provider,
    value = '',
    onChange,
  }: {
    picker: MediaPickerRune;
    provider: StorageProvider;
    value?: string;
    onChange: (folderId: string) => void;
  } = $props();

  let newFolderName = $state('');
  const canCreate = typeof provider.createFolder === 'function';

  async function handleCreate(): Promise<void> {
    const name = newFolderName.trim();
    if (!name) return;
    const folder = await picker.createFolder(provider, name);
    newFolderName = '';
    onChange(folder.id);
  }
</script>

<div class="flex flex-wrap items-center gap-2">
  <ModernSelect
    {value}
    disabled={picker.state.foldersLoading}
    onchange={onChange}
    options={[{ value: '', label: 'Todas las carpetas' }, ...picker.state.folders.map((folder) => ({ value: folder.id, label: folder.name }))]}
    placeholder="Todas las carpetas"
  />
  {#if picker.state.foldersError}
    <p role="alert" class="text-sm text-red-600">{picker.state.foldersError.message}</p>
  {/if}
  {#if canCreate}
    <span class="flex items-center gap-2">
      <input
        type="text"
        bind:value={newFolderName}
        placeholder="Nueva carpeta"
        class="rounded-md border border-zinc-300 px-2 py-1.5 text-sm"
      />
      <button
        type="button"
        onclick={handleCreate}
        class="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50"
      >
        Crear
      </button>
    </span>
  {/if}
</div>
