// packages/media-picker/ui/svelte/MediaLibraryGrid.svelte
<script lang="ts">
  import type { MediaPickerRune } from '../../adapters/svelte/create-media-picker.svelte.js';
  import type { LibraryItem } from '../../core/media-picker.js';

  let {
    picker,
    onSelectSingle,
  }: {
    picker: MediaPickerRune;
    onSelectSingle?: (item: LibraryItem) => void;
  } = $props();

  function handleClick(item: LibraryItem): void {
    if (onSelectSingle) {
      onSelectSingle(item);
      return;
    }
    picker.toggleLibrarySelection(item);
  }

  function isSelected(item: LibraryItem): boolean {
    return picker.state.selection.some((selected) => selected.key === item.key);
  }
</script>

<!--
  Deliberately unstyled: a plain grid of buttons, no CSS framework, no design polish — this
  package ships headless-first with minimal reference UI. Restyle freely.
-->
<div role="grid" aria-busy={picker.state.libraryLoading} style="display:grid;grid-template-columns:repeat(auto-fill, minmax(96px, 1fr));gap:8px">
  {#if picker.state.libraryError}
    <p role="alert">{picker.state.libraryError.message}</p>
  {/if}
  {#each picker.state.libraryItems as item (item.key)}
    <button
      type="button"
      aria-pressed={isSelected(item)}
      data-selected={isSelected(item)}
      onclick={() => handleClick(item)}
      style="border:{isSelected(item) ? '2px solid #333' : '1px solid #ccc'};padding:4px"
    >
      {#if item.mimeType?.startsWith('image/')}
        <img src={item.url} alt={item.key} style="width:100%;height:auto" />
      {:else}
        <span>{item.key}</span>
      {/if}
    </button>
  {/each}
</div>

// packages/media-picker/ui/react/MediaLibraryGrid.tsx
import type { JSX } from 'react';
import type { LibraryItem } from '../../core/media-picker.js';
import type { UseMediaPickerResult } from '../../adapters/react/use-media-picker.js';

export interface MediaLibraryGridProps {
  picker: UseMediaPickerResult;
  /** Called with the clicked item when `picker.state` was built without `multiple: true`. */
  onSelectSingle?: (item: LibraryItem) => void;
}

/**
 * Deliberately unstyled: a plain grid of buttons, no CSS framework, no design polish — this
 * package ships headless-first with minimal reference UI (see PRD non-goal on polished UI).
 * Consuming projects are expected to restyle this freely.
 */
export function MediaLibraryGrid({ picker, onSelectSingle }: MediaLibraryGridProps): JSX.Element {
  const { libraryItems, selection, libraryLoading, libraryError } = picker.state;
  const selectedKeys = new Set(selection.map((item) => item.key));

  const handleClick = (item: LibraryItem): void => {
    if (onSelectSingle) {
      onSelectSingle(item);
      return;
    }
    picker.toggleLibrarySelection(item);
  };

  return (
    <div
      role="grid"
      aria-busy={libraryLoading}
      style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(96px, 1fr))',
        gap: 8,
      }}
    >
      {libraryError ? <p role="alert">{libraryError.message}</p> : null}
      {libraryItems.map((item) => {
        const isSelected = selectedKeys.has(item.key);
        return (
          <button
            key={item.key}
            type="button"
            aria-pressed={isSelected}
            data-selected={isSelected}
            onClick={() => handleClick(item)}
            style={{ border: isSelected ? '2px solid #333' : '1px solid #ccc', padding: 4 }}
          >
            {item.mimeType?.startsWith('image/') ? (
              <img src={item.url} alt={item.key} style={{ width: '100%', height: 'auto' }} />
            ) : (
              <span>{item.key}</span>
            )}
          </button>
        );
      })}
    </div>
  );
}
