// packages/modals/ui/svelte/internal/OverlayBody.svelte
<script lang="ts">
  import { safeMessage } from '../../safe/message.js';
  import { safeColor, maxWidthClass } from '../../safe/style.js';
  import { safeHref, safeImageSrc } from '../../safe/url.js';

  import type { InteractionAction, ModalConfig } from '../../../core/types.js';

  let {
    config,
    ondismiss,
    class: extraClass = '',
  }: {
    config: ModalConfig;
    ondismiss: (action: InteractionAction) => void;
    class?: string;
  } = $props();

  const imageSrc = $derived(safeImageSrc(config.imageUrl));
  const primaryHref = $derived(safeHref(config.primaryButton?.url));
  const secondaryHref = $derived(safeHref(config.secondaryButton?.url));
  const bgColor = $derived(safeColor(config.bgColor));
  const textColor = $derived(safeColor(config.textColor));
  const showClose = $derived(config.showCloseButton ?? true);
  const message = $derived(safeMessage(config));
</script>

<div
  class="modals-body {maxWidthClass(config.maxWidth)} {extraClass}"
  style:background-color={bgColor}
  style:color={textColor}
>
  {#if showClose}
    <button type="button" class="modals-close" aria-label="Cerrar" onclick={() => ondismiss('close-button')}>×</button>
  {/if}
  {#if imageSrc}
    <img class="modals-image" src={imageSrc} alt="" referrerpolicy="no-referrer" />
  {/if}
  {#if config.title}
    <h2 class="modals-title">{config.title}</h2>
  {/if}
  {#if message.html}
    <div class="modals-message">{@html message.html}</div>
  {:else}
    <p class="modals-message">{message.text}</p>
  {/if}
  {#if config.primaryButton || config.secondaryButton}
    <div class="modals-actions">
      {#if config.primaryButton}
        {#if primaryHref}
          <a
            class="modals-button modals-button--primary"
            href={primaryHref}
            rel="noopener noreferrer"
            target="_blank"
            onclick={() => ondismiss('primary-button')}
          >
            {config.primaryButton.text}
          </a>
        {:else}
          <button type="button" class="modals-button modals-button--primary" onclick={() => ondismiss('primary-button')}>
            {config.primaryButton.text}
          </button>
        {/if}
      {/if}
      {#if config.secondaryButton}
        {#if secondaryHref}
          <a
            class="modals-button modals-button--secondary"
            href={secondaryHref}
            rel="noopener noreferrer"
            target="_blank"
            onclick={() => ondismiss('secondary-button')}
          >
            {config.secondaryButton.text}
          </a>
        {:else}
          <button type="button" class="modals-button modals-button--secondary" onclick={() => ondismiss('secondary-button')}>
            {config.secondaryButton.text}
          </button>
        {/if}
      {/if}
    </div>
  {/if}
</div>

// packages/modals/ui/react/internal/OverlayBody.tsx
import {
  maxWidthClass,
  safeHref,
  safeImageSrc,
  safeMessage,
  safeOverlayStyle,
} from './safe-render.js';

import type { ModalConfig } from '../../../core/types.js';

export interface OverlayBodyProps {
  config: ModalConfig;
  onPrimary: () => void;
  onSecondary: () => void;
  onClose: () => void;
  className?: string;
}

/** Shared presentational rendering (title/message/image/buttons/close) for every overlay type except Toast. */
export function OverlayBody({
  config,
  onPrimary,
  onSecondary,
  onClose,
  className,
}: OverlayBodyProps) {
  const message = safeMessage(config);
  const imageSrc = safeImageSrc(config.imageUrl);
  const primaryHref = safeHref(config.primaryButton?.url);
  const secondaryHref = safeHref(config.secondaryButton?.url);
  const showClose = config.showCloseButton ?? true;

  return (
    <div
      className={`modals-body ${maxWidthClass(config.maxWidth)} ${className ?? ''}`}
      style={safeOverlayStyle(config)}
    >
      {showClose && (
        <button type="button" className="modals-close" aria-label="Cerrar" onClick={onClose}>
          ×
        </button>
      )}
      {imageSrc && (
        <img className="modals-image" src={imageSrc} alt="" referrerPolicy="no-referrer" />
      )}
      {config.title && <h2 className="modals-title">{config.title}</h2>}
      {message.html ? (
        <div className="modals-message" dangerouslySetInnerHTML={{ __html: message.html }} />
      ) : (
        <p className="modals-message">{message.text}</p>
      )}
      {(config.primaryButton || config.secondaryButton) && (
        <div className="modals-actions">
          {config.primaryButton &&
            (primaryHref ? (
              <a
                className="modals-button modals-button--primary"
                href={primaryHref}
                rel="noopener noreferrer"
                target="_blank"
                onClick={onPrimary}
              >
                {config.primaryButton.text}
              </a>
            ) : (
              <button
                type="button"
                className="modals-button modals-button--primary"
                onClick={onPrimary}
              >
                {config.primaryButton.text}
              </button>
            ))}
          {config.secondaryButton &&
            (secondaryHref ? (
              <a
                className="modals-button modals-button--secondary"
                href={secondaryHref}
                rel="noopener noreferrer"
                target="_blank"
                onClick={onSecondary}
              >
                {config.secondaryButton.text}
              </a>
            ) : (
              <button
                type="button"
                className="modals-button modals-button--secondary"
                onClick={onSecondary}
              >
                {config.secondaryButton.text}
              </button>
            ))}
        </div>
      )}
    </div>
  );
}
