// packages/modals/ui/react/FullscreenOverlay.tsx
import { useEffect, useRef } from 'react';

import { createFocusTrap } from '../a11y/focus-trap.js';
import { prefersReducedMotion } from '../a11y/reduced-motion.js';
import { OverlayBody } from './internal/OverlayBody.js';
import { useEscapeKey } from './internal/use-escape-key.js';

import type { ModalConfig } from '../../core/types.js';

export interface FullscreenOverlayProps {
  config: ModalConfig;
  onDismiss: (
    action: 'primary-button' | 'secondary-button' | 'close-button' | 'outside-click',
  ) => void;
}

/** Full-viewport dialog for `type: 'fullscreen'` (shares the 'modal' slot). Focus-trapped, closes on Escape. */
export function FullscreenOverlay({ config, onDismiss }: FullscreenOverlayProps) {
  const dialogRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = dialogRef.current;
    if (!el) return;
    const trap = createFocusTrap(el);
    trap.activate();
    return () => trap.deactivate();
    // Re-run on config identity change (Code Review Finding), not just mount — see
    // ModalOverlay.tsx's identical comment for why a mount-only effect misses a same-type,
    // same-slot config swap.
  }, [config.id]);

  useEscapeKey(true, () => onDismiss('close-button'));

  return (
    <div
      ref={dialogRef}
      role="dialog"
      aria-modal="true"
      aria-label={config.title ?? config.name ?? 'Diálogo'}
      className={`modals-fullscreen${prefersReducedMotion() ? ' modals-no-motion' : ''}`}
    >
      <OverlayBody
        config={config}
        onPrimary={() => onDismiss('primary-button')}
        onSecondary={() => onDismiss('secondary-button')}
        onClose={() => onDismiss('close-button')}
      />
    </div>
  );
}

// packages/modals/ui/svelte/vanilla/FullscreenOverlay.svelte
<script lang="ts">
  import '../../vanilla-styles.css';
  import { createFocusTrap } from '../../a11y/focus-trap.js';
  import { prefersReducedMotion } from '../../a11y/reduced-motion.js';
  import OverlayBody from './internal/OverlayBody.svelte';

  import type { InteractionAction, ModalConfig } from '../../../core/types.js';

  let {
    config,
    ondismiss,
  }: {
    config: ModalConfig;
    ondismiss: (action: InteractionAction) => void;
  } = $props();

  let dialogEl: HTMLDivElement | undefined = $state();

  $effect(() => {
    // See ModalOverlay.svelte's identical comment: reading `config.id` makes it a tracked
    // dependency so this re-runs on a same-type slot swap, not just on mount (Code Review Finding).
    void config.id;
    if (!dialogEl) return;
    const trap = createFocusTrap(dialogEl);
    trap.activate();
    return () => trap.deactivate();
  });

  $effect(() => {
    function onKeydown(event: KeyboardEvent): void {
      if (event.key === 'Escape') ondismiss('close-button');
    }
    document.addEventListener('keydown', onKeydown);
    return () => document.removeEventListener('keydown', onKeydown);
  });

  const noMotionClass = $derived(prefersReducedMotion() ? ' modals-no-motion' : '');
</script>

<div
  bind:this={dialogEl}
  role="dialog"
  aria-modal="true"
  aria-label={config.title ?? config.name ?? 'Diálogo'}
  class="modals-fullscreen mc-modals-fullscreen{noMotionClass}"
>
  <OverlayBody {config} {ondismiss} />
</div>
