// packages/auth-kit/ui/vue/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue';

import { buildLoginSchema, extractFieldError } from '../../core/validation.js';
import TurnstileWidget from './TurnstileWidget.vue';

import type { UseAuthKitResult } from '../../adapters/vue/use-auth-kit.js';
import type { TurnstileFieldConfig } from '../../core/field-config.js';

const props = defineProps<{ authKit: UseAuthKitResult; turnstile?: TurnstileFieldConfig }>();

const identifier = ref('');
const password = ref('');
const showPassword = ref(false);
const turnstileToken = ref<string | null>(null);
const fieldErrors = ref<Record<string, string>>({});


/** Clears a field's stale error message as soon as the user edits it, instead of leaving it displayed until the next submit. */
function clearError(key: string): void {
  if (key in fieldErrors.value) {
    const next = { ...fieldErrors.value };
    delete next[key];
    fieldErrors.value = next;
  }
}

/** Validates a single field on blur — shows that field's error immediately instead of waiting for submit. */
function validateField(key: string): void {
  const result = buildLoginSchema().safeParse({ identifier: identifier.value, password: password.value });
  const message = extractFieldError(result, key);
  if (message) {
    fieldErrors.value = { ...fieldErrors.value, [key]: message };
  } else {
    clearError(key);
  }
}

function handleSubmit(): void {
  const result = buildLoginSchema().safeParse({ identifier: identifier.value, password: password.value });
  if (!result.success) {
    fieldErrors.value = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
    return;
  }
  fieldErrors.value = {};
  void props.authKit
    .login({ identifier: identifier.value, password: password.value, turnstileToken: turnstileToken.value })
    .catch(() => {});
}
</script>

<!-- Headless variant — no CSS classes, fully consumer-styleable. Same props/behavior across every presentation. -->
<template>
  <form novalidate @submit.prevent="handleSubmit">
    <div>
      <label for="auth-kit-login-identifier">Correo electrónico o nombre de usuario</label>
      <input id="auth-kit-login-identifier" v-model="identifier" @input="clearError('identifier')" @blur="validateField('identifier')" type="text" autocomplete="username" />
      <p v-if="fieldErrors.identifier" role="alert">{{ fieldErrors.identifier }}</p>
    </div>
    <div>
      <label for="auth-kit-login-password">Contraseña</label>
      <input id="auth-kit-login-password" v-model="password" @input="clearError('password')" @blur="validateField('password')" :type="showPassword ? 'text' : 'password'" autocomplete="current-password" />
      <button type="button" @click="showPassword = !showPassword">{{ showPassword ? 'Ocultar' : 'Mostrar' }}</button>
      <p v-if="fieldErrors.password" role="alert">{{ fieldErrors.password }}</p>
    </div>
    <TurnstileWidget
      v-if="turnstile?.enabled"
      :site-key="turnstile.siteKey"
      :theme="turnstile.theme"
      :mode="turnstile.mode"
      @token="(t) => (turnstileToken = t)"
    />
    <button type="submit" :disabled="authKit.state.value.login.status === 'submitting'">
      {{ authKit.state.value.login.status === 'submitting' ? 'Iniciando sesión…' : 'Iniciar sesión' }}
    </button>
    <p v-if="authKit.state.value.login.status === 'error' && authKit.state.value.login.error" role="alert">
      {{ authKit.state.value.login.error.message }}
    </p>
    <p v-if="authKit.state.value.login.status === 'success'">Sesión iniciada.</p>
  </form>
</template>

// packages/auth-kit/ui/angular/login-form.component.ts
import { NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';

import { buildLoginSchema, extractFieldError } from '../../core/validation.js';
import { TurnstileWidgetComponent } from './turnstile-widget.component.js';

import type { AuthKitService } from '../../adapters/angular/auth-kit.service.js';
import type { TurnstileFieldConfig } from '../../core/field-config.js';

/** Headless variant — no CSS classes, fully consumer-styleable. Same props/behavior across every presentation. */
@Component({
  selector: 'auth-kit-login-form',
  standalone: true,
  imports: [NgIf, TurnstileWidgetComponent],
  template: `
    <form novalidate (submit)="handleSubmit($event)">
      <div>
        <label for="auth-kit-login-identifier">Correo electrónico o nombre de usuario</label>
        <input
          id="auth-kit-login-identifier"
          type="text"
          autocomplete="username"
          [value]="identifier"
          (input)="identifier = $any($event.target).value; clearError('identifier')" (blur)="validateField('identifier')"
        />
        <p *ngIf="fieldErrors['identifier']" role="alert">{{ fieldErrors['identifier'] }}</p>
      </div>
      <div>
        <label for="auth-kit-login-password">Contraseña</label>
        <input
          id="auth-kit-login-password"
          [type]="showPassword ? 'text' : 'password'"
          autocomplete="current-password"
          [value]="password"
          (input)="password = $any($event.target).value; clearError('password')" (blur)="validateField('password')"
        />
        <button type="button" (click)="showPassword = !showPassword">{{ showPassword ? 'Ocultar' : 'Mostrar' }}</button>
        <p *ngIf="fieldErrors['password']" role="alert">{{ fieldErrors['password'] }}</p>
      </div>
      <auth-kit-turnstile-widget
        *ngIf="turnstile?.enabled"
        [siteKey]="turnstile?.siteKey"
        [theme]="turnstile?.theme"
        [mode]="turnstile?.mode"
        (token)="turnstileToken = $event"
      ></auth-kit-turnstile-widget>
      <button type="submit" [disabled]="authKit.state().login.status === 'submitting'">
        {{ authKit.state().login.status === 'submitting' ? 'Iniciando sesión…' : 'Iniciar sesión' }}
      </button>
      <p *ngIf="authKit.state().login.status === 'error' && authKit.state().login.error" role="alert">
        {{ authKit.state().login.error?.message }}
      </p>
      <p *ngIf="authKit.state().login.status === 'success'">Sesión iniciada.</p>
    </form>
  `,
})
export class LoginFormComponent {
  @Input({ required: true }) authKit!: AuthKitService;
  @Input() turnstile?: TurnstileFieldConfig;

  identifier = '';
  password = '';
  showPassword = false;
  turnstileToken: string | null = null;
  fieldErrors: Record<string, string> = {};

  
  /** Clears a field's stale error message as soon as the user edits it, instead of leaving it displayed until the next submit. */
  clearError(key: string): void {
    if (key in this.fieldErrors) {
      const next = { ...this.fieldErrors };
      delete next[key];
      this.fieldErrors = next;
    }
  }

  /** Validates a single field on blur — shows that field's error immediately instead of waiting for submit. */
  validateField(key: string): void {
    const result = buildLoginSchema().safeParse({ identifier: this.identifier, password: this.password });
    const message = extractFieldError(result, key);
    if (message) {
      this.fieldErrors = { ...this.fieldErrors, [key]: message };
    } else {
      this.clearError(key);
    }
  }

  handleSubmit(event: Event): void {
    event.preventDefault();
    const result = buildLoginSchema().safeParse({ identifier: this.identifier, password: this.password });
    if (!result.success) {
      this.fieldErrors = Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]));
      return;
    }
    this.fieldErrors = {};
    void this.authKit
      .login({ identifier: this.identifier, password: this.password, turnstileToken: this.turnstileToken })
      .catch(() => {});
  }
}
